"""OpenAI-compatible chat client.

Points at any server exposing POST /v1/chat/completions — this is exactly
the interface vLLM serves when it runs a model on AMD Instinct GPUs via
ROCm (`vllm serve <model> --host 0.0.0.0`). Swapping LLM_BASE_URL is all
that's needed to move from a laptop to AMD Developer Cloud.
"""
import json
import random
import time
from typing import List, Dict

import httpx

from .config import settings


class LLMError(RuntimeError):
    pass


def chat(messages: List[Dict[str, str]]) -> str:
    if settings.llm_provider == "mock":
        return _mock_chat(messages)
    return _vllm_chat(messages)


def _vllm_chat(messages: List[Dict[str, str]]) -> str:
    url = f"{settings.llm_base_url.rstrip('/')}/chat/completions"
    payload = {
        "model": settings.llm_model,
        "messages": messages,
        "temperature": 0.2,
        "max_tokens": 512,
    }
    headers = {"Authorization": f"Bearer {settings.llm_api_key}"}
    try:
        resp = httpx.post(url, json=payload, headers=headers, timeout=settings.request_timeout_s)
        resp.raise_for_status()
    except httpx.HTTPError as exc:
        raise LLMError(f"Could not reach LLM server at {url}: {exc}") from exc
    data = resp.json()
    try:
        return data["choices"][0]["message"]["content"]
    except (KeyError, IndexError) as exc:
        raise LLMError(f"Unexpected LLM response shape: {data}") from exc


_MOCK_LATENCY_S = 0.15


def _mock_chat(messages: List[Dict[str, str]]) -> str:
    """Deterministic stand-in agent brain for local/offline development.

    It looks at how many steps have already happened (by counting prior
    "observation" turns in the transcript) and returns the next ReAct step
    as JSON, ending after 2 tool calls with a final answer.
    """
    time.sleep(_MOCK_LATENCY_S)
    goal = next((m["content"] for m in messages if m["role"] == "user"), "")
    observations = sum(1 for m in messages if m["role"] == "tool")

    if observations == 0:
        return json.dumps({
            "thought": f"I should search the web for information about: {goal}",
            "action": "web_search",
            "action_input": goal,
        })
    if observations == 1:
        return json.dumps({
            "thought": "I have some search results, let me fetch the most relevant page for details.",
            "action": "fetch_url",
            "action_input": "https://example.com",
        })
    return json.dumps({
        "thought": "I have enough information to answer.",
        "final_answer": (
            f"Mock summary for '{goal}'. Configure LLM_PROVIDER=vllm and "
            f"LLM_BASE_URL to point at a real model served on AMD GPUs."
        ),
        "results": [
            {
                "title": f"Overview: {goal}"[:80],
                "detail": "This is a placeholder result generated by the mock LLM provider.",
                "source_url": "https://example.com",
            }
        ],
    })
